tasks:
- sequential:
  - upgrade-tasks
  - workload-tasks

upgrade-tasks:
  sequential:
    - cephadm.shell:
        host.a:
          - ceph config set mon mon_warn_on_insecure_global_id_reclaim false --force
          - ceph config set mon mon_warn_on_insecure_global_id_reclaim_allowed false --force
          - ceph config set global log_to_journald false --force
          - ceph orch upgrade start --ceph-version 18.2.4
    - cephadm.shell:
        host.a:
          - while ceph orch upgrade status | jq '.in_progress' | grep true && ! ceph orch upgrade status | jq '.message' | grep Error ; do ceph orch ps ; ceph versions ; ceph fs dump; ceph orch upgrade status ; ceph health detail ; sleep 30 ; done
          - ceph orch ps
          - ceph orch upgrade status
          - ceph health detail
          - ceph versions
          - echo "wait for servicemap items w/ changing names to refresh"
          - sleep 60
          - ceph orch ps
          - ceph versions
          - ceph versions | jq -e '.overall | length == 1'
          - ceph versions | jq -e '.overall | keys' | grep "18.2.4"

workload-tasks:
  sequential:
    - tasks:
        - cephfs_test_runner:
            modules:
              - tasks.cephfs.test_quota
