overrides:
  ceph-fuse:
    disabled: true
  kclient:
    disabled: true
  install:
    ceph:
      extra_system_packages:
      - python3-pytest
tasks:
- workunit:
    clients:
      client.0:
        - fs/test_python.sh
