overrides:
  ceph-fuse:
    disabled: true
  kclient:
    disabled: true

tasks:
- install:
    extra_system_packages:
      - python3-pytest
- workunit:
    clients:
      client.0:
        - fs/test_python.sh
